### ISSUE TITLE
Latest Offset Updater

### ISSUE THREAD

**Issue by mr-mosh** [ErectusTestus/ErectusExperimental#1]
Yo EB, hope you are well - somewhat worried that you have completely vanished. 

If you happen to see this, could you please upload the latest version of the Offset Updater to GitHub? 

I've noticed that the last version I could find was not catching the correct offsets, and was actually missing a few of the newer ones in v8.

Cheers and stay safe.

**Comment by WaGi-Coding** [comment]
Also noticed it. It was hard to find this post in first place ^^
So if ErectBAN ever reappears, it would be nice to add the offset updater into this or it's own dedicated repository.

Thanks for all your work so far, wish you the best.

**Comment by slingblade2047** [comment]
I have uploaded the offset updater source to my github page. It worked with the new exe but returned a lot of 0 entries. I am not versed enough to try to make changes but you are more than welcome to use it to get it to work. Let me know if I can be of further assistance.

**Comment by mr-mosh** [comment]
> I have uploaded the offset updater source to my github page. It worked with the new exe but returned a lot of 0 entries. I am not versed enough to try to make changes but you are more than welcome to use it to get it to work. Let me know if I can be of further assistance.

That's right. The version you have on your github was the Offset Updater for v6 (covering to 1.3.0.23) - the same I've used. If you compare the output with the offsets in Erectus v8, you'll see that quite a few of them are new there - and a lot have changed, probably because their respective signature has changed in 1.3.1.26 and more so now in 1.3.1.34.

To adjust, we would have to analyse the new signatures in 1.3.1.34, but sadly, I do not have IDA or ErectBAN's experience to know what to look for. 

I am well aware that without trying, I never will. So I'm just hopeful that the man comes back and says "Gee, can't a man have a break?" and resumes working on this :-)

**Comment by slingblade2047** [comment]
i have Ghidra to use and I a m trying to figure things out. But with no formal knowledge, I am at an impass.  The analyzer takes hours or more. I will try to analtze the new one and see what can be done. No promises.....................

**Comment by Striker0420** [comment]
Im working on using a modified ce to see if can trace back some functions and i need to learn about opcodes more

**Comment by GittyAub** [comment]
I wish God🧙‍♀️speed to you Sling🗡2047.😊👍
May she help guide you to a new techno👩‍💻friend who'll help in your endeavour.
Same wishes to you Striker0420, Mr-Mosh, and WaGi-Coding.
Maybe some of you should pool resources, if you are not already.
Cheers,
GittyAub.

**Comment by ifaab** [comment]
i JUST CAN´T FIGURE IT OUT... IM SORRY FRIENDS... WE NEED ERECTUS CLASSES ONCE AGAIN.

**Comment by GodGameMod** [comment]
![v8](https://user-images.githubusercontent.com/33415800/84388703-9a42ea00-ac27-11ea-885d-c14c358df01a.png)

![v18](https://user-images.githubusercontent.com/33415800/84388992-058cbc00-ac28-11ea-91c1-36192d76b53f.png)


all done.I'm waiting for the next update

**Comment by WaGi-Coding** [comment]
well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^

**Comment by GodGameMod** [comment]
> well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^

I think erectban has good things to do, so erectban gave up update

**Comment by slingblade2047** [comment]
> > well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^
> 
> I think erectban has good things to do, so erectban gave up update

That’s amazing that you were able to get the rest of the offsets. Are you able to share, especially when the new up múdate comes out? Additionally, we’re there any new implementations to the anticheat protocols they have in place?

**Comment by GodGameMod** [comment]
> > > well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^
> > 
> > 
> > I think erectban has good things to do, so erectban gave up update
> 
> That’s amazing that you were able to get the rest of the offsets. Are you able to share, especially when the new up múdate comes out? Additionally, we’re there any new implementations to the anticheat protocols they have in place?

I don't know at present. I didn't go to PTS either. I have to wait for the update

**Comment by slingblade2047** [comment]
> > > > well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^
> > > 
> > > 
> > > I think erectban has good things to do, so erectban gave up update
> > 
> > 
> > That’s amazing that you were able to get the rest of the offsets. Are you able to share, especially when the new up múdate comes out? Additionally, we’re there any new implementations to the anticheat protocols they have in place?
> 
> I don't know at present. I didn't go to PTS either. I have to wait for the update

Fair. Are you able to share the source for the updater so that we can keep this project alive? I can post to my repository. Let me know.

**Comment by GodGameMod** [comment]
> > > > > well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^
> > > > 
> > > > 
> > > > I think erectban has good things to do, so erectban gave up update
> > > 
> > > 
> > > That’s amazing that you were able to get the rest of the offsets. Are you able to share, especially when the new up múdate comes out? Additionally, we’re there any new implementations to the anticheat protocols they have in place?
> > 
> > 
> > I don't know at present. I didn't go to PTS either. I have to wait for the update
> 
> Fair. Are you able to share the source for the updater so that we can keep this project alive? I can post to my repository. Let me know.

You should see me in the next version

**Comment by slingblade2047** [comment]
> > > > > > well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^
> > > > > 
> > > > > 
> > > > > I think erectban has good things to do, so erectban gave up update
> > > > 
> > > > 
> > > > That’s amazing that you were able to get the rest of the offsets. Are you able to share, especially when the new up múdate comes out? Additionally, we’re there any new implementations to the anticheat protocols they have in place?
> > > 
> > > 
> > > I don't know at present. I didn't go to PTS either. I have to wait for the update
> > 
> > 
> > Fair. Are you able to share the source for the updater so that we can keep this project alive? I can post to my repository. Let me know.
> 
> You should see me in the next version

That’s cool. I think it drops next week. Did you want the PTS EXE? I have that if you need it.

**Comment by GodGameMod** [comment]
> > > > > > > well this issue only gets abused by autists now. I can understand why erectban lost motivation ^^
> > > > > > 
> > > > > > 
> > > > > > I think erectban has good things to do, so erectban gave up update
> > > > > 
> > > > > 
> > > > > That’s amazing that you were able to get the rest of the offsets. Are you able to share, especially when the new up múdate comes out? Additionally, we’re there any new implementations to the anticheat protocols they have in place?
> > > > 
> > > > 
> > > > I don't know at present. I didn't go to PTS either. I have to wait for the update
> > > 
> > > 
> > > Fair. Are you able to share the source for the updater so that we can keep this project alive? I can post to my repository. Let me know.
> > 
> > 
> > You should see me in the next version
> 
> That’s cool. I think it drops next week. Did you want the PTS EXE? I have that if you need it.

do you know how to dump ? i need dump .if you know , u can send dump to my email:nfbesports@gmail.com

**Comment by mr-mosh** [comment]
@GodGameMod, what's unclear to me is, why do you have to wait until the next update?

If all 1.3.1.34 introduced were different offsets, and you have them and the vtables now, why can't you just share them so that we can get a "v8.1" going?

I appreciate that the next update may change the need to have more/other/altered vtables and offsets, and that would intrinsically require code changes. But if we know what they are now, can we just get it going please?

**Comment by slingblade2047** [comment]
I am not very fluent in all of this. I do not have a modified CE to use. Unless you can take a dump made by windows. That I can assist with. Either that or I can upload the PTS EXE to mega for download.

**Comment by GodGameMod** [comment]
download teamviewer and send me a remote code email

**Comment by slingblade2047** [comment]
> download teamviewer and send me a remote code email

Are you looking to remote into my computer to run the program?

**Comment by GodGameMod** [comment]
> > download teamviewer and send me a remote code email
> 
> Are you looking to remote into my computer to run the program?

no,u run ,and copy code send my email.

**Comment by slingblade2047** [comment]
> > > download teamviewer and send me a remote code email
> > 
> > 
> > Are you looking to remote into my computer to run the program?
> 
> yeah bro

I see. No offense and I am sure that you can understand any apprehensions I may have as I would like to know what purpose this would serve? Can you let me know what is going to be done?

**Comment by GodGameMod** [comment]
> > > > download teamviewer and send me a remote code email
> > > 
> > > 
> > > Are you looking to remote into my computer to run the program?
> > 
> > 
> > yeah bro
> 
> I see. No offense and I am sure that you can understand any apprehensions I may have as I would like to know what purpose this would serve? Can you let me know what is going to be done?

u dont know hot to dump ,so  i can show how to dump,that's all ,If you don't want to,just wait game update

**Comment by mr-mosh** [comment]
Yeah, no, don't fall for this scam...
